    LIST	P=16F887
    #INCLUDE	<P16F887.INC>
    
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
    
    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    CBLOCK  0x20
    DIG1    ;LBS20
    DIG2    ;MBS21
    T1	    ;22
    T2	    ;23
    T3	    ;24
    CONT1   ;25
    CONT2   ;26
    WSAVE   ;27
    STSAVE  ;28
    ADCRES  ;29
    FLAG    ;30
    AUX	    ;30
    ENDC
    
    ORG	    0x00
    GOTO    MAIN
    ORG	    0x04
    GOTO    ISR
    ORG	    0x05
    
MAIN
    CALL    SETPORTS
    CALL    SETISR
    CALL    DISPLAY
    GOTO    $-1

ISR
    CALL    SAVECONTEXT
    BTFSC   INTCON,0
    CALL    RBFLAG
    BTFSC   INTCON,2
    CALL    TMR0FLAG
    BANKSEL PORTA
    BTFSC   FLAG,0
    CALL    BCD
    CALL    RETCONTEXT
    RETFIE
    
SETPORTS
    ;PORTA ADC
    ;PORTB BOTON
    ;PORTC MULTIPLEXADO
    ;PORTD DISPLAY
    MOVLW   0x01
    BANKSEL TRISA
    MOVWF   TRISA
    
    BANKSEL TRISB
    MOVWF   TRISB
    CLRF    TRISC
    CLRF    TRISD
    
    BANKSEL ANSEL
    MOVLW   0x01
    MOVWF   ANSEL
    
    BANKSEL ANSELH
    CLRF    ANSELH
    
    BANKSEL IOCB
    BSF	    IOCB,0
    
    BANKSEL PORTA
    CLRF    PORTD
    CLRF    PORTD
    MOVLW   .126
    MOVWF   CONT1
    MOVLW   .5	    ; SE CAMBIA A 5 PARA EL ARMADO FISICO
    MOVWF   CONT2
    
    CLRF    DIG1
    CLRF    DIG2
    
    RETURN
    
SETISR
    BANKSEL OPTION_REG
    MOVLW   0x07
    MOVWF   OPTION_REG
    
    BANKSEL INTCON
    MOVLW   0x88
    MOVWF   INTCON
    
    RETURN
; SALVA EL CONTEXTO    
SAVECONTEXT
    BANKSEL PORTA
    MOVWF   WSAVE
    MOVF    STATUS,W
    MOVWF   STSAVE
    
    RETURN
; RECUPERA EL CONTEXTO    
RETCONTEXT
    BANKSEL PORTA
    MOVF    STSAVE,W
    MOVWF   STATUS
    MOVF    WSAVE,W
    
    RETURN
    
RBFLAG
    CALL    SETTMR0
    ;DESHABILITO LAS FUTURAS INTERRUPCIONES POR PUERTOB
    ;HASTA QUE TERMINE LA CONVERSION DEL ADC
    BCF	    INTCON,3
    BCF	    INTCON,0    
    BSF	    INTCON,5
    
    RETURN

; DECREMENTA CONT1 Y SI CONT1 = 0, LLAMA A DECCONT2
; SINO RESETEA EL TMR0
TMR0FLAG
    BCF	    STATUS,Z
    BANKSEL PORTA
    DECF    CONT1
    BTFSS   STATUS,Z
    CALL    SETTMR0
    BTFSC   STATUS,Z
    CALL    DECCONT2
    BCF	    INTCON,2
    
    RETURN
; DECREMENTA CONT2 Y SI CONT2 = 0, LLAMA A CONVERTER
; SINO RESETEA EL TMR0
DECCONT2
    BCF	    STATUS,Z
    BANKSEL PORTA
    DECF    CONT2
    BTFSS   STATUS,Z
    CALL    RESETCONT1
    BTFSC   STATUS,Z
    CALL    CONVERTER
    ;BSF	    FLAG,1
    
    RETURN
; RESETEA EL CONT1 Y VUELVE A SETEAR EL TMR0
RESETCONT1
    MOVLW   .126
    MOVWF   CONT1
    CALL    SETTMR0
    
    RETURN
; SETEA EL TIMER0 CON EL VALOR 224 DECIMAL
SETTMR0
    BANKSEL TMR0
    MOVLW   .224
    MOVWF   TMR0
    
    RETURN

CONVERTER
    BANKSEL ADCON1
    MOVLW   0x00
    MOVWF   ADCON1
    
    BANKSEL ADCON0
    MOVLW   0xC1
    MOVWF   ADCON0
    CALL    ADQTIME
    BSF	    ADCON0,1
    BTFSC   ADCON0,1
    GOTO    $-1
    
    BANKSEL ADRESH
    MOVF    ADRESH,W
    
    BANKSEL PORTA
    MOVWF   ADCRES
    MOVF    ADCRES,W
    ADDWF   ADCRES,F
    
    BSF	    FLAG,0
    BCF	    FLAG,1
    
    MOVLW   .126
    MOVWF   CONT1
    MOVLW   .5
    MOVWF   CONT2
    
    BSF	    INTCON,3
    BCF	    INTCON,2
    BCF	    INTCON,5
    
    RETURN
    
BCD
    BANKSEL PORTA 
    CLRF    DIG1
    CLRF    DIG2
    MOVF    ADCRES,W
    MOVWF   AUX
    MOVLW   .10
    ADDWF   AUX,F
ATRAS
    
    MOVLW   .10
    SUBWF   AUX,F
    MOVLW   .10
    SUBWF   ADCRES,F
    BTFSC   STATUS,C
    INCF    DIG2
    BTFSC   STATUS,C
    GOTO    ATRAS
    MOVF    AUX,W
    MOVWF   DIG1
    BCF	    FLAG,0

    RETURN
    

DISPLAY
    BANKSEL PORTD
    MOVF    DIG1,W
    CALL    TABLE
    MOVWF   PORTD
    BSF	    PORTC,0
    ;CALL    DELAY	    ;AL QUEMAR EN EL PIC SE LO SACA
    BCF	    PORTC,0
    MOVF    DIG2,W
    CALL    TABLE
    MOVWF   PORTD
    BSF	    PORTC,1
    ;CALL    DELAY	    ;AL QUEMAR EN EL PIC SE LO SACA
    BCF	    PORTC,1
    
    RETURN
    

    
TABLE
    ADDWF   PCL,F
    RETLW   0xC0    ; 0
    RETLW   0xF9    ; 1
    RETLW   0xA4    ; 2
    RETLW   0xB0    ; 3
    RETLW   0x99    ; 4
    RETLW   0x92    ; 5
    RETLW   0x82    ; 6
    RETLW   0xF8    ; 7
    RETLW   0x80    ; 8
    RETLW   B'10011000'
    RETLW   B'10001000' ; A
    RETLW   B'10000011' ; B
    RETLW   B'11000110' ; C
    RETLW   B'10100001' ; D
    RETLW   B'10001110' ; E
    RETLW   B'10000110' ; F
    
DELAY
    BANKSEL PORTA
    MOVLW   .100
    MOVWF   T1
ALFA
    DECFSZ  T1
    GOTO    ALFA
    RETURN
    
DELAY50MS
    BANKSEL PORTA
    MOVLW   .50
    MOVWF   T2
BETA1
    MOVLW   .255
    MOVWF   T1
ALFA1
    DECFSZ  T1
    GOTO    ALFA1
    DECFSZ  T2
    GOTO    BETA1
    RETURN
    
ADQTIME
    BANKSEL PORTA
    MOVLW   .20
    MOVWF   T1
BETA
    DECFSZ  T1
    GOTO    BETA
    RETURN
    
    END